- hosts: webservers # Host or group
  become: true
  vars:
    httpd_port: 8080
  tasks:
    -name: Install httpd # Name of task for debugging
     yum: name=http state=present # Using module
    -name: Start httpd
     service: name=httpd state=started


- hosts: dbservers # Host or group
  become: true
  vars:
    httpd_port: 8080
  tasks:
    -name: Install mysql # Name of task for debugging
     yum: name=mysql state=present # Using module
    -name: Start mysql
     service: name=mysql state=mysql
