---
- hosts: webservers # Host or group
  become: true
  tasks:
    - name: Install httpd # Name of task for debugging
      yum: name=httpd state=present # Using module
    - name: Start httpd
      service: name=httpd state=started


- hosts: dbservers # Host or group
  become: true
  tasks:
    - name: Install mysql-server # Name of task for debugging
      yum: name=mysql-server state=latest # Using module
    - name: Start mysql
      service: name=mysql-server state=started
